### ISSUE TITLE
field "aperio.ImageID" not found

### ISSUE THREAD

**Issue by halynyu** [Steven-N-Hart/dicom_wsi#22]
* dicom-wsi version: 1.0.3
* Python version: 3.9.16
* Operating System: ubuntu 20.04

Hi,
I have completed all the installations, and I have also checked that the example file is converted well. So I tried with another .svs file that I wanted to convert, but
**pyvips.error.Error: unable to get aperio.ImageID
vips_image_get: field "aperio.ImageID" not found**
error occured.
I'm not sure whether this issue is related to annotation. How can I fir this error?
![스크린샷_20230220_045526](https://user-images.githubusercontent.com/120549760/220046576-c17460a7-b42c-459f-a78e-db2e24d84ff1.png)

**Comment by Steven-N-Hart** [comment]
resolved in #v.1.0.4
