### ISSUE TITLE
First time installation on Docker failed because libreadline-gplv2-dev is not available

### ISSUE THREAD

**Issue by thchong** [Steven-N-Hart/dicom_wsi#24]
* dicom-wsi version: 12/21/2021
* Python version: 3.10.8
* Operating System: Windows 11

### Description
First time installation on Docker failed because libreadline-gplv2-dev is not available. 

### What I Did
After cloning the master, I ran the docker build.

C:\Users\thoma\Documents\dicom_wsi>docker build -t dicom_wsi .
[+] Building 12.5s (7/11)                                                                                docker:default
 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 2B                                                                                    0.0s
 => [internal] load build definition from Dockerfile                                                               0.0s
 => => transferring dockerfile: 2.25kB                                                                             0.0s
 => [internal] load metadata for docker.io/library/ubuntu:latest                                                   1.0s
 => [1/8] FROM docker.io/library/ubuntu@sha256:2b7412e6465c3c7fc5bb21d3e6f1917c167358449fecac8176c6e496e5c1f05f    4.0s
 => => resolve docker.io/library/ubuntu@sha256:2b7412e6465c3c7fc5bb21d3e6f1917c167358449fecac8176c6e496e5c1f05f    0.0s
 => => sha256:2b7412e6465c3c7fc5bb21d3e6f1917c167358449fecac8176c6e496e5c1f05f 1.13kB / 1.13kB                     0.0s
 => => sha256:c9cf959fd83770dfdefd8fb42cfef0761432af36a764c077aed54bbc5bb25368 424B / 424B                         0.0s
 => => sha256:e4c58958181a5925816faa528ce959e487632f4cfd192f8132f71b32df2744b4 2.30kB / 2.30kB                     0.0s
 => => sha256:aece8493d3972efa43bfd4ee3cdba659c0f787f8f59c82fb3e48c87cbb22a12e 29.54MB / 29.54MB                   2.5s
 => => extracting sha256:aece8493d3972efa43bfd4ee3cdba659c0f787f8f59c82fb3e48c87cbb22a12e                          1.4s
 => [2/8] RUN mkdir /data                                                                                          0.6s
 => [3/8] RUN apt-get -y update                                                                                    5.5s
 => ERROR [4/8] RUN apt-get install -y build-essential python3.6 python3-pip python3-dev cython3 checkinstall cma  1.3s
------
 > [4/8] RUN apt-get install -y build-essential python3.6 python3-pip python3-dev cython3 checkinstall cmake default-jdk git libreadline-gplv2-dev libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev liblcms2-dev libtiff-dev libpng-dev libvips libvips-dev libz-dev libbz2-dev libjpeg-dev openslide-tools unzip python3-openslide wget xutils-dev zlib1g-dev libopenjp2-7-dev  python3-gdcm:
0.478 Reading package lists...
1.094 Building dependency tree...
1.250 Reading state information...
1.285 Package libreadline-gplv2-dev is not available, but is referred to by another package.
1.285 This may mean that the package is missing, has been obsoleted, or
1.285 is only available from another source
1.285
1.287 E: Package 'libreadline-gplv2-dev' has no installation candidate
------
Dockerfile:7
--------------------
   5 |     # INSTALL PYTHON AND DEPENDENCIES
   6 |     RUN apt-get -y update
   7 | >>> RUN apt-get install -y build-essential python3.6 python3-pip python3-dev cython3 checkinstall cmake default-jdk git libreadline-gplv2-dev libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev liblcms2-dev libtiff-dev libpng-dev libvips libvips-dev libz-dev libbz2-dev libjpeg-dev openslide-tools unzip python3-openslide wget xutils-dev zlib1g-dev libopenjp2-7-dev  python3-gdcm
   8 |     RUN pip3 install numpy
   9 |     RUN pip3 install git+https://github.com/Who8MyLunch/CharPyLS
--------------------
ERROR: failed to solve: process "/bin/sh -c apt-get install -y build-essential python3.6 python3-pip python3-dev cython3 checkinstall cmake default-jdk git libreadline-gplv2-dev libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev liblcms2-dev libtiff-dev libpng-dev libvips libvips-dev libz-dev libbz2-dev libjpeg-dev openslide-tools unzip python3-openslide wget xutils-dev zlib1g-dev libopenjp2-7-dev  python3-gdcm" did not complete successfully: exit code: 100

**Comment by thchong** [comment]
Correction:
dicom-wsi version: 2/12/2021

**Comment by Steven-N-Hart** [comment]
resolved in #v.1.0.4
