### ISSUE TITLE
First time miniconda-based installation on Linux failed on requirements_dev.txt pip install

### ISSUE THREAD

**Issue by thchong** [Steven-N-Hart/dicom_wsi#25]
* dicom-wsi version: Feb 12, 2021
* Python version:  3.12.0
* Operating System: Debian GNU/Linux 11 (bullseye)

### Description
First time miniconda-based installation on Linux failed on pip install of the requirements_dev.txt.

### What I Did
$pip install -U -r requirements_dev.txt
....
Collecting openslide-wrapper==1.1.2 (from -r requirements_dev.txt (line 26))
  Downloading openslide-wrapper-1.1.2.tar.gz (315 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 315.3/315.3 kB 4.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting packaging>=19.2 (from -r requirements_dev.txt (line 27))
  Downloading packaging-23.2-py3-none-any.whl.metadata (3.2 kB)
Collecting pathtools>=0.1.2 (from -r requirements_dev.txt (line 28))
  Downloading pathtools-0.1.2.tar.gz (11 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
 
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-yrgbr5qu/pathtools_8a286064f97f48489caa56e6ad4bade8/setup.py", line 25, in <module>
          import imp
      ModuleNotFoundError: No module named 'imp'
      [end of output]
 
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

**Comment by Steven-N-Hart** [comment]
resolved in #v.1.0.4
